//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Cantidad { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
