//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.ORDERSDETAILS = new HashSet<ORDERSDETAILS>();
            this.SHIPMENTS = new HashSet<SHIPMENTS>();
        }
    
        public int Order_Id { get; set; }
        public long CedulaUsuario { get; set; }
        public int ProductID { get; set; }
        public int Cantidad { get; set; }
        public double TotalCompra { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public int IdVenta { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual SALES SALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERSDETAILS> ORDERSDETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIPMENTS> SHIPMENTS { get; set; }
    }
}
