//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERSDETAILS
    {
        public int OrderDetailId { get; set; }
        public int Amount { get; set; }
        public int OrderId { get; set; }
        public int Price { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
    }
}
