//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.CART = new HashSet<CART>();
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public int ProductID { get; set; }
        public string Nombre { get; set; }
        public int ValorUni { get; set; }
        public int Lote { get; set; }
        public System.DateTime Fecha_Vencimiento { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> CategorieId { get; set; }
        public Nullable<int> CompanieNit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART> CART { get; set; }
        public virtual CATEGORIES CATEGORIES { get; set; }
        public virtual COMPANIES COMPANIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
