//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIAL_ACTIVITIES
    {
        public string Codigo_Eventualidad { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Detalles { get; set; }
        public string Order_Id { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
    }
}
